# 1차시: Python 을 활용한 데이타 분석 학습평가

## 1일차

1. 오차행렬의 TN 과 TP 의 차이를 설명하시오.

> 둘 다 정확히 분류된 샘플을 의미. TN 은 음성을 정답으로 분류한 것이고 TP는 양성을 정답으로 분류한 것

2. p-value 란 무엇인가 ?

> 유의확률로 귀무가설이 맞다고 가정할 때 얻은 결과보다 극단적인 결과가 실제로 관측될 확률

3. type([1,2,3])의 결과를 서술하시오.

> list

4. rainfall 이 90% 이상이면 우산이라는 출력을, 그렇지 않으면 양산이라는 출력을 하는 코드를 작성하시오

```
if rainfall >= 0.9:
   print('우산')
else:
   print('양산')

```

5. 덧셈과 곱셈 함수를 def 를 활용해 코드를 작성하시오.

```
def add(a, b):
   return a+b
   
def multiply(a, b):
   return a*b
```

## 2일차

1. numpy 의 특징을 두가지만 쓰시오.

> 내장된 python 연산보다 빠르다. 효율적인 배열처리로 다차원행렬 등 고수준 연산에 강하다

2. pandas Series 와 DataFrame 의 차이를 서술하시오.

> Series: 1차원 벡터 데이타에 행방향 인덱스를 붙인 것. DataFraem: 인덱스와 컬럼이 존재하는 2차원 행렬이며 데이타 테이블 구조

3. 0부터 8까지 값을 갖는 3x3 행렬을 만드시오

```
import numpy as np

m = np.arange(0, 9).reshape(3, 3)
print(m)

```

4. 위에서 만든 행렬에서 최소값을 갖는 코드를 작성하시오

> print(m.min())

5. 0~15의 랜덤 숫자로 4x4 DataFrame을 만드는 코드를 작성하시오.

```
import pandas as pd
print(pd.DataFrame(np.random.randint(0, 16, (4,4))))
```


## 3일차

1. 데이타를 시각화해야하는 이유는 ?

> 방대하거나 고차원의 데이타일수록 필요하며 쉽고 빠르게 이해하기 위해 필요

2. boxplot과 violinplt 의 특징적 차이를 서술하시오.

> boxplot은 중앙값, 표준편차 등 분포의 간략한 특성만 보여주는데 반해, violinplot은 확률밀도까지 시각화하여 카테고리값에 따른 각 분포의 확인 가능

3. violinplot을 사용하기 위해 필요한 seaborn 라이브러리를 sns로 정의하고 import 하시오

> import seaborn as sns

4. 결측치(NaN)을 가지고 있는 행들을 지워주는 코드를 작성하시오.

```python
dates = pd.date_range('20190101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 3), index=dates, columns=list('ABC'))
df2 = df1.reindex(index=dates[0:4], columns=list(df1.columns) + ['D'])
df1.loc[dates[1]:dates[2], 'D'] = 1
```

> df1.dropna(how='any')

5. df2의 새로운 열로 Z 데이타를 추가하는 코드를 작성하시오. Z 는 모두 0

> df2['Z'] = 0


## 4일차

1. pandas 에서 표준편차를 구하는 함수는 무엇인가 

> std

2. pandas 에서 그룹화할 때 사용하는 함수는 무엇인가

> groupby


[3-5]문제 참고

```python

df = pd.read_csv('https://raw.githubusercontent.com/blackdew/dplus-tensorflow/master/csv/Graduate_apply.csv', sep=',', skipinitialspace=True, engine='python')
df.head()

```

3. rank 컬럼의 dummy variable 얻기

> df_rank = pd.get_dummies(df['rank']); df_rank.head()

4. dummy 와 원래 데이타 합치기

> df_new = pd.concat([df, df_rank], axis=1); df_new.head()

5. rank 컬럼 제거하기

> df_new = df_new.drop('rank', axis=1); df_new.head()


## 5일차

> 1000이하의 모든 소수를 구하는 프로그램을 작성하고 아래의 물음에 답하시오

```python
primes = []

for i in range(2, 1001):
    if np.any(list(map(lambda x: i % x == 0, primes))) == False:
        primes.append(i)
```

1. 1000 이하 소수는 몇개 ?

> len(primes) = 168

2. 1000 이하 소수를 모두 더하면 ?

> np.sum(primes) = 76127

3. 1000 이하 소수의 중간값은 얼마인가 ?

> np.median(primes) = 436

# 2차시: 머신러닝 알고리즘 이해 학습평가

* [실습 1차시](http://bit.ly/2l8K2bp)
* [실습 2차시](http://bit.ly/2mKJTLX)

## 실습 1차시

In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

db = load_diabetes()
print(db.DESCR)
####### 원본 데이터를 찾아서 가져왔음
####### 원본 데이터를 찾아서 가져왔음
temp = pd.read_csv('https://web.stanford.edu/~hastie/Papers/LARS/diabetes.data',sep = '\t')
temp.head()
temp['SEX'] = temp['SEX']-1
x = temp.drop(['Y'], axis = 1)
y = temp[['Y']]

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.
(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)

# Q1. 12번째 row의   S2컬럼의 값은 무엇인가?

In [20]:
x.loc[12,'S2']

109.2

In [21]:
x

     AGE  SEX   BMI      BP   S1     S2    S3    S4      S5   S6
0     59    1  32.1  101.00  157   93.2  38.0  4.00  4.8598   87
1     48    0  21.6   87.00  183  103.2  70.0  3.00  3.8918   69
2     72    1  30.5   93.00  156   93.6  41.0  4.00  4.6728   85
3     24    0  25.3   84.00  198  131.4  40.0  5.00  4.8903   89
4     50    0  23.0  101.00  192  125.4  52.0  4.00  4.2905   80
..   ...  ...   ...     ...  ...    ...   ...   ...     ...  ...
437   60    1  28.2  112.00  185  113.8  42.0  4.00  4.9836   93
438   47    1  24.9   75.00  225  166.0  42.0  5.00  4.4427  102
439   60    1  24.9   99.67  162  106.6  43.0  3.77  4.1271   95
440   36    0  30.0   95.00  201  125.2  42.0  4.79  5.1299   85
441   36    0  19.6   71.00  250  133.2  97.0  3.00  4.5951   92

[442 rows x 10 columns]

# Q2. min-max scailing 후, 12번째 row의 s2컬럼의 값은 무엇인가?

**조건**
1. S1~ S6 만 스케일링 할 것
1. 소수점 세자리까지, 그 미만 절삭.
2. 0번째 row부터 있습니다.

# Linear Regression 모델링을 한 후 다음 질문들에 답하여라.

**조건**
1. train/valid/test 분리하지 않는다.
2. 모든 데이터를 이용한 예측값을 **y_pred**에 담는다.